# Generated by Django 5.1.3 on 2025-01-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
